// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssetHandler() {
  return window['go']['main']['App']['AssetHandler']();
}

export function GetReaderManifest(arg1) {
  return window['go']['main']['App']['GetReaderManifest'](arg1);
}

export function GetReaderProgress(arg1) {
  return window['go']['main']['App']['GetReaderProgress'](arg1);
}

export function GetSettings() {
  return window['go']['main']['App']['GetSettings']();
}

export function ListDownloadJobs() {
  return window['go']['main']['App']['ListDownloadJobs']();
}

export function ListLibraryManga() {
  return window['go']['main']['App']['ListLibraryManga']();
}

export function PauseJob(arg1) {
  return window['go']['main']['App']['PauseJob'](arg1);
}

export function QueueChapters(arg1) {
  return window['go']['main']['App']['QueueChapters'](arg1);
}

export function ResolveManga(arg1) {
  return window['go']['main']['App']['ResolveManga'](arg1);
}

export function ResumeJob(arg1) {
  return window['go']['main']['App']['ResumeJob'](arg1);
}

export function RetryFailed(arg1) {
  return window['go']['main']['App']['RetryFailed'](arg1);
}

export function ScanLocalState(arg1) {
  return window['go']['main']['App']['ScanLocalState'](arg1);
}

export function UpdateReaderProgress(arg1) {
  return window['go']['main']['App']['UpdateReaderProgress'](arg1);
}

export function UpdateSettings(arg1) {
  return window['go']['main']['App']['UpdateSettings'](arg1);
}
