// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {http} from '../models';
import {contracts} from '../models';

export function AssetHandler():Promise<http.Handler>;

export function GetReaderManifest(arg1:string):Promise<contracts.ReaderManifest>;

export function GetSettings():Promise<contracts.AppSettings>;

export function ListDownloadJobs():Promise<Array<contracts.DownloadJob>>;

export function ListLibraryManga():Promise<Array<contracts.LibraryManga>>;

export function PauseJob(arg1:string):Promise<void>;

export function QueueChapters(arg1:contracts.QueueDownloadRequest):Promise<contracts.DownloadJob>;

export function ResolveManga(arg1:string):Promise<contracts.ParsedMangaResult>;

export function ResumeJob(arg1:string):Promise<void>;

export function RetryFailed(arg1:string):Promise<void>;

export function ScanLocalState(arg1:string):Promise<Array<contracts.LocalChapterState>>;

export function UpdateSettings(arg1:contracts.AppSettings):Promise<contracts.AppSettings>;
